version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blog
      MYSQL_DATABASE: blog_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

  backend:
    build: .  # Set to the current directory
    container_name: backend_container
    restart: always
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: blog
      DATABASE_NAME: blog_db
      NODE_ENV: development  # Set environment variable
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - backend_network
    command: npx nodemon server.mjs

networks:
  backend_network:

volumes:
  mysql_data:
